### ISSUE TITLE
I got an email about some maintenance for Iris - now it doesnt work

### ISSUE THREAD

**Issue by Aviator85** [apexad/node-iris-aladdin-connect-garage-door#3]
So a few weeks back Iris sent and email out and said they some services wouldnt be available because they were going to be doing maintenance and upgrades. Since then my home app just says updating. It never connects. It was working just fine(thanks to the helpful folks here) and now its not, nothing else has changed.

**Comment by relic982** [comment]
Restart your homebridge, iris hub, phone and whatever device is your homekit hub (Apple TV most likely).

Iris sends those updates frequently to announce their firmware updates.

**Comment by apexad** [comment]
I am unable to duplicate this issue.  Iriis constantly updates as @relic982 mentoned.

Confirm it still works in the Iris app.  If it does not, start there.

Otherwise check to confirm your password and such is correct in your setup files.

If all that checks out and it's still not working, you'll need to post some log from homebridge so I can see what is happening.

**Comment by Aviator85** [comment]
Problem wasn't with the node-iris-aladdin-connect-garage-door, it was with homebridge-garage-command. When it updated it deleted my config files with login credentials, just copied my back up files back in and badda-bing good to go.
